// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zcmuhokuysnotekmqzpj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjbXVob2t1eXNub3Rla21xenBqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2ODQyNDAsImV4cCI6MjA1ODI2MDI0MH0.Www6iUGk8omJ3N5dvfN_zIBbzLAvEtbaRDYFYJEy018";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);